<?php
	$this->Html->setHead('css','sistema_usuarios_login');
	$inputUsu['input'] = array('value'=>'admin@phpgrid.com','class'=>'form-control','placeholder'=>'e-mail','autofocus'=>'autofocus','div'=>array('style'=>'margin-bottom: 5px;'));
	$inputEma['input'] = array('value'=>'1234567','type'=>'password','placeholder'=>'senha','class'=>'form-control');
?>
<div class='container-fluid'>
	<br />
	<center>
	<!-- <img src='<?= $base ?>img/angu.png' width='130px' /> -->
	<h1>
		<?= SISTEMA ?>
		<?php if (AMBIENTE!='PRODUÇÃO') : ?> (<span style='color: red; font-size: 18px;'><?= AMBIENTE ?></span>)<?php endif ?>
	</h1>
	</center>
	<br />
</div>

<div id='login' class="container">
	<form id='formLogin' method='post' action='' class="form-horizontal">

	<?= $this->Html->getInput('Usuario.email',$inputUsu); ?>
	<?= $this->Html->getInput('Usuario.senha',$inputEma); ?>

	<div style='float: left; line-height: 34px; margin: 10px 0px 0px 0px;'>
		<input type='submit' value='Enviar' id='btEnviar' class='btn btn-large btn-primary' />
	</div>

	<div style='float: right; line-height: 40px; margin: 6px 0px 0px 0px;'>
		<a href='<?= $base ?>sistema/usuarios/esqueci_a_senha'>esqueci a senha</a> |
		<a href='<?= $base ?>sistema/usuarios/registro'>registrar</a>
	</div>

	</form>
</div>
<br />
<div class="container">

<?php if (isset($erroBanco)) : ?>
<div style='margin: 0px auto; width: 600px; padding: 3px; line-height: 30px; text-align: center; color: red;'>
<?= $erroBanco ?>
</div>
<center>
	Clique <a href='<?= getBase() ?>sistema/usuarios/instala_tb'>aqui</a> para continuar a instalação.
</center>
<br /><br />
<?php endif ?>


<center>
	<a href='<?= $base ?>'>Volta para a página inicial</a>
</center>

</div>
