<style>
	.upload
	{
		margin: 10px auto;
		width: 500px;
		border: 1px solid #ccc;
		padding: 5px;
		background-color: #fff;
	}
	.upload label
	{
		display: block;
		float: left;
		text-align: right;
		min-width: 150px;
		margin: 0px 5px 0px 0px;
	}
</style>
<div class='upload'>
	<form method="post" action="" enctype="multipart/form-data">
		<div>
			<label>Imagem: </label>
			<input type="file" name="img" />
		</div>
		
		<div style='clear: both; margin-top: 10px;'>
			<label>Altura: </label>
			<input type="text" name="red" value='500' style='width: 60px; text-align: center;' />&nbsp; pixels
		</div>
		<div style='clear: both; margin-top: 20px;'>
		<b>OBS:</b>
		<p>
			- A Largura será proporcional à altura.<br />
			- Serão aceitas apenas imagens do tipo .PNG, .GIF e .JPG<br />
		</p>
		</div>
		<br />
		<input type="submit" value="Enviar" class='btn btn-success' />
		<input type="button" value="Fechar" class='btn btn-close' onclick='history.go(-1);' />
	</form>
</div>

<?php if (isset($name)) : ?>
<center>
<p>O novo arquivo foi criado com sucesso em:<br /><b><?= $base ?>uploads/<?= $name ?></b></p>
<img src='<?= $base.'uploads/'.$name ?>' />
</center>
<?php endif ?>

<?php if (isset($erro)) : ?>
<center>
<p style="color: red;">
<?= $erro ?>
</p>
</center>
<?php endif ?>
