<div id="padrao_ferramentas">

	<div style='float: left;'>
	<?php if (isset($this->viewVars['ferramentasLayout'])) : foreach($this->viewVars['ferramentasLayout'] as $_l => $_arrProp) : ?>
		<img title='<?= $_arrProp['title'] ?>' src='<?= $_arrProp['icone'] ?>' onclick='<?= $_arrProp['onclick'] ?>' />
	<?php endforeach; endif ?>
	</div>

	<div style='float: left; margin: 0px 0px 0px 10px;'>
		<form name='formPerfil' method='post' action='<?= getBase() ?>sistema/usuarios/troca_perfil/'>
		<select name='data[Usuario][perfil]' id='UsuarioTPerfil' title='Clique aqui para trocar o perfil ...' onchange='setPerfil(this.value);'>
			<?php foreach($_SESSION['Perfis'] as $_id => $_nome) : ?>
			<option value='<?= $_id ?>' <?php if ($_nome==$_SESSION['Usuario']['perfil']) echo ' selected="selected"'; ?> >
				<?= $_nome ?>
			</option>
			<?php endforeach ?>
		</select>
		</form>
	</div>

</div>
