<?php

	$pagA = ($this->viewVars['paginacao']['pag']-1);
	if ($pagA<1) $pagA = 1;

	$pagP = ($this->viewVars['paginacao']['pag']+1);
	if ($pagP>$this->viewVars['paginacao']['pagU']) $pagP = $this->viewVars['paginacao']['pagU'];

	$link1 = $this->viewVars['base'].strtolower($module.'/'.$controller.'/listar/pag:1/ord:'.$this->viewVars['params']['ord'].'/dir:'.$this->viewVars['params']['dir']);
	$linkA = $this->viewVars['base'].strtolower($module.'/'.$controller.'/listar/pag:'.$pagA.'/ord:'.$this->viewVars['params']['ord'].'/dir:'.$this->viewVars['params']['dir']);
	$linkP = $this->viewVars['base'].strtolower($module.'/'.$controller.'/listar/pag:'.$pagP.'/ord:'.$this->viewVars['params']['ord'].'/dir:'.$this->viewVars['params']['dir']);
	$linkU = $this->viewVars['base'].strtolower($module.'/'.$controller.'/listar/pag:'.$this->viewVars['paginacao']['pagU'].'/ord:'.$this->viewVars['params']['ord'].'/dir:'.$this->viewVars['params']['dir']);
?>
<div class='paginacao'>
<ul>
  <li><a href="<?= $link1 ?>">&laquo;</a></li>
  <li><a href="<?= $linkA ?>">&lsaquo;</a></li>

  <li><?= $this->viewVars['paginacao']['pag'] ?></li>

  <li><a href="<?= $linkP ?>">&rsaquo;</a></li>
  <li><a href="<?= $linkU ?>">&raquo;</a></li>
</ul>

</div>