<div id='permissoes'>
	<input type='hidden' disabled='disabled' name='data[Permissao][module]' 	value='<?= strtolower($this->viewVars['module']) ?>' />
	<input type='hidden' disabled='disabled' name='data[Permissao][controller]' value='<?= strtolower($this->viewVars['controller']) ?>' />
	<input type='hidden' disabled='disabled' name='data[Permissao][action]'		value='<?= strtolower($this->viewVars['action']) ?>' />
	
	<input type='checkbox' id='PermissaoVisualizar' name='data[Permissao][visualizar'] />
	<label for='PermissaoVisualizar'>Visualizar</label>

	<input type='checkbox' id='PermissaoIncluir' name='data[Permissao][incluir'] />
	<label for='PermissaoIncluir'>Incluir</label>

	<input type='checkbox' id='PermissaoAlterar' name='data[Permissao][alterar'] />
	<label for='PermissaoAlterar'>Alterar</label>

	<input type='checkbox' id='PermissaoExcluir' name='data[Permissao][excluir'] />
	<label for='PermissaoExcluir'>Excluir</label>
	
	&nbsp;&nbsp;
	<input type='button' name='btPerSal' id='btPerSal' value='Salvar' 	onclick='alert("aqui vou salvar ...");' >
	<input type='button' name='btPerFec' id='btPerFec' value='Cancelar' onclick='$("#permissoes").fadeOut(400);'>
</div>
