<?php if (isset($sql_dump) && count($sql_dump)) : ?>
<div id='sql_dump' class='container-fluid'>
<table border='1' width='100%'>
	<tr>
		<th>##</th>
		<th>sql</th>
		<th>linhas</th>
		<th>tempo (seg)</th>
	</tr>
	<?php foreach($sql_dump as $_l => $_arrSqls) : ?>
	<tr>
		<td align='center' width='50px'><?= ($_l+1) ?></td>
		<td
		<?php 
			if ($_arrSqls['sql']=='BEGIN;') echo "class='td_begin'"; 
			if ($_arrSqls['sql']=='COMMIT;') echo "class='td_commit'"; 
			if ($_arrSqls['sql']=='ROLLBACK;') echo "class='td_rollback'"; 
		?>
		><?= $_arrSqls['sql'] ?></td>
		<td align='center' width='50px'><?= $_arrSqls['li'] ?></td>
		<td align='center' width='110px'><?= $_arrSqls['ts'] ?></td>
	</tr>
	<?php endforeach ?>
</table>
</div>

<?php endif; ?>
