<form name='formLista' id='formLista' method='post' action='<?= $base.strtolower($module).'/'.strtolower($controller).'/salvar' ?>' >
<table class='tabLista'><!-- linhas -->
<input type='hidden' name='urlRetorno' value='<?= $this->viewVars['urlRetorno'] ?>' style='width: 300px;' />
<input type='hidden' name='marcador' value='' id='marcador' style='width: 300px;' />
<?php foreach($this->data as $_l => $_arrMods) : ?>

<?php if (!$_l) : ?>
<tr><!-- cabeçalho das linhas -->
	<?php if ($this->Html->pode('alterar',$this->viewVars['minhasPermissoes']) 
			&& isset($this->viewVars['marcadores'])) : ?>
		<th>
		<input type='checkbox' name='cxAll' id='cxAll' title='clique aqui para selecionar todos'
		<?php
		array_push($this->viewVars['onRead'], '$("#cxAll").click(function(event) 
		{
			if (this.checked==true)
				$(".cxLista").each(function() { this.checked = true; });
			else
				$(".cxLista").each(function() { this.checked = false; });
		})');
		?>
		/>
		</th>
	<?php endif ?>

	<?php if (isset($this->viewVars['ferramentas']) && count($this->viewVars['ferramentas'])) : ?>
	<th style='text-align: center;' colspan='<?= count($this->viewVars['ferramentas']); ?>'>#</th>
	<?php endif ?>

	<?php
	foreach($this->viewVars['fields'] as $_l2 => $_cmp) : 
	$c = $_cmp;
	$a = explode('.',$_cmp); 
	$d = ($this->viewVars['params']['dir']=='asc') ? 'desc' : 'asc';
	$p = $this->viewVars['esquema'][$a['0']][$a['1']];
	$i = isset($this->viewVars['esquema'][$a['0']][$a['1']]['key']) ? true : false; // é indice
	$t = isset($p['tit']) ? $p['tit'] : $a['1'];
	$ty= isset($p['type']) ? $p['type'] : null;
	$i = ($ty=='habtm') ? false : $i;
	if (isset($p['belongsTo']))
	{
		$c = $this->Html->getFieldRel($p['belongsTo']);
	}

	$l = $base.strtolower($module.'/'.$controller.'/listar/pag:'
		.$this->viewVars['params']['pag'].'/ord:'.str_replace('.', '_', $c).'/dir:'.$d);
	?>
	<th class="th<?= $this->Html->domId($a['1']) ?>">
		<?php if ($i) : ?>
		<a href='<?= $l ?>'><?= $t ?></a>
		<?php else : ?>
		<?= $t ?>
		<?php endif ?>

		<?php
		 	if ($this->Html->pode('pesquisar',$this->viewVars['minhasPermissoes'])) : 
			if (isset($p['pesquisar'])) : 
			if ($p['pesquisar']==true) $p['pesquisar']=='='; 
		?>
		<img id='imgFormPes<?= $a['1'] ?>' class='imgFormPes' 
			src='<?= $this->viewVars['base'] ?>img/bt_pesquisar.png' onclick='showFormPesquisa("<?= $a['1'] ?>")' 
			title='Clique aqui para executar uma pesquisa no campo <?= $t ?>';
		/>
		<div id='divFormPes<?= $a['1'] ?>' class='clFormPes'>
			<input type='hidden' id='tipFormPes<?= $a['1'] ?>' value='<?= $p['pesquisar'] ?>' class='tipFormPes' />
			<input type='text' 	 id='cmpFormPes<?= $a['1'] ?>' class='cmpFormPes' />
		</div>
		<?php endif; endif ?>
		
	</th>
	<?php endforeach ?>
</tr>
<?php endif ?>

<?php if (isset($this->viewVars['erros'][($_l+1)])) : ?>
<tr>
	<td colspan='100' class='td_lista_erro'>
		<?= $this->viewVars['erros'][($_l+1)] ?>
	</td>
</tr>
<?php endif ?>

<tr><!-- linha a linha -->
	<?php if ($this->Html->pode('alterar',$this->viewVars['minhasPermissoes']) && isset($this->viewVars['marcadores'])) : ?>
	<td>
		<?php
			$ids = '';
			foreach($this->viewVars['primaryKey'] as $_l3 => $_cmp3) 
			{
				if ($_l3) $ids .= ',';
				$ids .= $_cmp3.'='.$_arrMods[$this->viewVars['modelClass']][$_cmp3];
			}
		?>
		<input type='checkbox' class='cxLista' name='cx[<?= $ids ?>]' id='cx<?= ($_l+1) ?>' />
	</td>
	<?php endif ?>

	<?php // loop nas ferramentas de cada linha
		if (isset($this->viewVars['ferramentas'])) :
		foreach($this->viewVars['ferramentas'] as $_fer => $_prop) : 
		$_prop['title'] = isset($_prop['title']) ? $_prop['title'] : $_fer;
		$arqBt 			= 'bt_'.$_fer.'.png';
		if (strpos($_prop['link'], '*')) // substituindo o campo pelo valor do campo
		{
			foreach($this->viewVars['primaryKey'] as $_l2 => $_cmp)
			{ 
				$v = $_arrMods[$this->viewVars['modelClass']][$_cmp];
				$_prop['link'] = str_replace('*'.$_cmp.'*', $v, $_prop['link']);
			}
		}
		?>
		<td align='center'>
			<a href='<?= $_prop['link'] ?>' 
			<?php if (isset($_prop['onclick'])) : ?>
				onclick="<?= $_prop['onclick'] ?>"
			<?php endif; ?>
			>
				<img src='<?= $base ?>img/<?= $arqBt ?>' title='<?= $_prop['title'] ?>' /> 
			</a>
		</td>
	<?php endforeach; endif ?>

	<?php  // loop nos campos para escrever a coluna de cada linha
		foreach($this->viewVars['primaryKey'] as $_l3 => $_cmp3) // campos primários
		{
			echo "<input type='hidden' value='".$_arrMods[$a['0']][$_cmp3]
				."' name='data[".($_l+1)."][".$this->viewVars['modelClass']."][".$_cmp3."]' />";
		}
		foreach($this->viewVars['fields'] as $_l2 => $_cmp) : 
			$a = explode('.',$_cmp);
			$p = $this->viewVars['esquema'][$a['0']][$a['1']];
			$cmp = ($_l+1).'.'.$a['0'].'.'.$a['1'];
			$p['value'] = isset($_arrMods[$a['0']][$a['1']]) ? $_arrMods[$a['0']][$a['1']] : null;
			if ($p['type']=='habtm' && isset($_arrMods[$a['1']]))
			{
				$p['value'] = $_arrMods[$a['1']];
			}
	?>
		<td id='td<?= $this->Html->domId(($_l+1).'.'.$a['1']) ?>' class="td<?= $this->Html->domId($a['1']) ?>">
			<?php
				$pode = $this->Html->pode('alterar',$this->viewVars['minhasPermissoes']);
				if (!$pode)  $p['edicaoOff'] = true;

				echo $this->Html->getInput($cmp,$p,$this->data[$_l]);
				if (isset($p['mascara']))
				{
					array_push($this->viewVars['onRead'],'$("#'.$this->Html->domId($cmp).'").mask("'.str_replace('#','9',$p['mascara']).'")');
				}
			?>
		</td>
	<?php endforeach ?>
</tr>

<?php endforeach ?>
</form>

<?php if (isset($this->viewVars['paginacao']['tot'])) : ?>
<tr style='background-color: transparent; border: none;'>
	<td colspan='100' style='padding-left: 5px; background-color: transparent; border: none;'>
	Total de registros: <?= number_format($this->viewVars['paginacao']['tot'],0,',','.'); ?>
</td></tr>
</table><!-- fim linhas -->
<?php endif ?>



