<?php
	$this->Html->setHead('css','lista');
	$this->Html->setHead('js','lista');
	$this->Html->setHead('js','jquery.maskedinput.min');
?>

<?php $this->element('ajax_form'); ?>

<div id='lista'>

	<div style='width: 200px; min-height: 500px; float: left; margin: 0px 3px 0px 0px;'><!-- menu lista -->
		<?php $this->element('menu_lista'); ?>

	</div><!-- fim menu lista -->

	<div style='display: table;'><!-- direita -->

		<?php $this->element('tabela_novo'); ?>

		<div id='dir1' style='margin: 0px 0px 5px 0px;'>
			<?php $this->element('botoes_lista'); ?>
		</div>

		<div id='dir11' style='line-height: 30px;'>
			<?php if (isset($this->viewVars['paginacao'])) : ?>
				<?php $this->element('paginacao') ?>
			<?php endif ?>

			<?php if (isset($this->viewVars['marcadores']) && count($this->viewVars['marcadores'])) : ?>
			<div class='marcadores'>
			<select name='cxSel' id='cxSel' >
				<option value=''>-- Aplicar aos Marcadores --</option>
				<?php foreach($this->viewVars['marcadores'] as $_txt => $_link) : ?>
					<option value='<?= $_link ?>'><?= $_txt ?></option>
				<?php endforeach ?>
			</select>
			</div>
			<?php endif ?>

			<?php if ($this->Html->pode('pesquisar',$this->viewVars['minhasPermissoes']) && 
					 (isset($this->viewVars['filtros']) && !empty($this->viewVars['filtros']))) : 
			?>
			<?php echo $this->element('filtro'); ?>
			<?php endif ?>

		</div>

		<div id='dir2' class='tabela'><!-- tabela -->
			<?php $this->element('tabela'); ?>
		</div><!-- fim tabela -->

	</div><!-- fim direita -->

</div><!-- fim lista -->
